version: '3.9'

services:
  php-8.0: &php
    build: docker/php-8.0
    container_name: braze-php-sdk-8.0
    working_dir: /app
    tty: true
    volumes:
      - .:/app:cached
  php-8.1:
    <<: *php
    build: docker/php-8.1
    container_name: braze-php-sdk-8.1
  php-8.2:
    <<: *php
    build: docker/php-8.2
    container_name: braze-php-sdk-8.2
