services:
  php-81: &php
    build: docker/php-8.1
    container_name: braze-php-sdk-8.1
    working_dir: /app
    tty: true
    volumes:
      - .:/app:cached
  php-82:
    <<: *php
    build: docker/php-8.2
    container_name: braze-php-sdk-8.2
  php-83:
    <<: *php
    build: docker/php-8.3
    container_name: braze-php-sdk-8.3
